# Generated by Django 4.2 on 2023-04-29 17:44

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_menu_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='test.menuitem'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
